---
title: "Assignment 5 module 9"
author: "wliu16"
date: "2022-11-4"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/tammyliu/Desktop/R/64018-004/Assignment module 9")
```

**1. Express y1+ and y1-; y2+ and y2-; P using x1, x2, x3**

$$y_1^+ - y_1^- = 50 - 6 x1 - 4 x2 - 5 x3;$$

$$y_2^+ - y_2^- = 75 - 8 x1 - 7 x2 - 5 x3;$$
$$P = 20 x_1 + 15 x_2 + 25 x_3;$$
<br>  

**2. Express management objective function**<br>  

$$Max \hspace{.2cm}Z = 20 x_1 + 15 x_2 + 25 x_3 - 6 y_1^+ - 6 y_1^- - 3 y_2^-$$
**3. Formulate and solve LP** 
```{r}
library(lpSolveAPI)
gp_sl <- read.lp("dewright.lp")
gp_sl
```

```{r}
solve(gp_sl)
get.objective(gp_sl)
get.variables(gp_sl)
```
<br> 

**Conclusion** <br>  
x1=x2=0, x3=15, y1p=25, y1m=y2m=y2p=0. Profit is 25*15= 325 millions of dollars. 
Employment is 7500 which has 2500 employees more than the goal so y1p=25, y1m=0.
Earnings next year is 75 millions of dollars which is the same with the goal
so y2m=y2p=0.
